### ISSUE TITLE
Connection to SKR1.3

### ISSUE THREAD

**Issue by mawa85** [bigtreetech/BIGTREETECH-TMC2209-V1.2#1]
Got them today, what exactly do I need to do to connect them to the SKR 1.3 in UART mode?

Thanks

**Comment by buddybu** [comment]
This is what I would like to know as well.  From what I can tell, you need to remove all other jumpers (Except the USB one), set the drivers in the socket.  and put a jumper (shunt) on the UART pins next to each driver module, X, Y, Z, E0...

But I cannot get sensorless homing to work for me.  Not sure why.

**Comment by bobathefetts** [comment]
check out the videos on youtube by "Teaching Tech"

**Comment by Jumbu** [comment]
Why don't you close your issue now
