### ISSUE TITLE
BTT SKR1.3+BTT TMC2209 sound & vibration issue

### ISSUE THREAD

**Issue by jazzroutine** [bigtreetech/BIGTREETECH-TMC2209-V1.2#2]
I have very strange issue with my new SKR 1.3 board and TMC2209 from BBT. Please see attached video with sound ON.

Video: https://youtu.be/lpWGFX8TAkM

StealthChop working in veeery strange way. Terrible vibrations and noise. If I change TMC mode to SpreadCycle, everything became almost normal, but there is still some minor vibrations and flow instability, as result outer walls are not smooth.

Only if I change speed to very low - less then 5 mm\s sound is disappearing.
2209 in UART mode. M122 output below. Latest Marlin 2.0 from git.

Really need some help here. I'm out of ideas T_T Something is really wrong here.

Already tried to change:
MINIMUM_STEPPER_PULSE - no effect
MINIMUM_STEPPER_POST/PRE_DIR_DELAY - no effect
ADAPTIVE_STEP_SMOOTHING - no effect
SQUARE_WAVE_STEPPING - no effect
Latest BTT TMC libraries - no effect
Steps per mm - no effect
Current - 600, 900, 1200 - no effect
LA - no effect

Conf: https://pastebin.com/dVAjzp83 
Conf_adv:  https://pastebin.com/FV86Mdy1 
M122 output: https://pastebin.com/jV13Aa3p

**Comment by jazzroutine** [comment]
Solved it. Moved to another TMC repo in platformio.ini:
```
[env:LPC1768]
platform          = https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.2.zip
framework         = arduino
board             = nxp_lpc1768
build_flags       = -DU8G_HAL_LINKS -IMarlin/src/HAL/HAL_LPC1768/include -IMarlin/src/HAL/HAL_LPC1768/u8g ${common.build_flags}
# debug options for backtrace
#  -funwind-tables
#  -mpoke-function-name
lib_ldf_mode      = off
lib_compat_mode   = strict
extra_scripts     = Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py
src_filter        = ${common.default_src_filter} +<src/HAL/HAL_LPC1768>
monitor_speed     = 250000
lib_deps          = Servo
  LiquidCrystal
  U8glib-HAL=https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip
  #TMCStepper=https://github.com/p3p/TMCStepper/archive/pr_lpctimingfix.zip #not ok
  TMCStepper=https://github.com/teemuatlut/TMCStepper/archive/master.zip #ok
  Adafruit NeoPixel=https://github.com/p3p/Adafruit_NeoPixel/archive/release.zip
  SailfishLCD=https://github.com/mikeshub/SailfishLCD/archive/master.zip
```

**Comment by freighttt** [comment]
I have this same problem, the repository didn’t solve it though.

**Comment by gretzke** [comment]
did you manage to solve it?

**Comment by jazzroutine** [comment]
> did you manage to solve it?

yeah :) 
The main issue was with ferrite filters. I use them as additional filter between the mainboard and step motors. After I removed them and moved to another repo, everything started work without problems.
