### ISSUE TITLE
SKR 1.4 Turbo and TMC2209

### ISSUE THREAD

**Issue by statiealexandru** [bigtreetech/BIGTREETECH-TMC2209-V1.2#6]
Motors not turning in UART mode (working in standalone):

SENDING:M122
		X	Y	Z	E
Address		0	0	0	0
Enabled		false	false	false	false
Set current	800	800	800	800
RMS current	795	795	795	795
MAX current	1121	1121	1121	1121
Run current	25/31	25/31	25/31	25/31
Hold current	12/31	12/31	12/31	12/31
CS actual	12/31	12/31	12/31	12/31
PWM scale	14	14	14	14
vsense		1=.18	1=.18	1=.18	1=.18
stealthChop	false	true	true	true
msteps		32	16	16	16
tstep		max	max	max	max
PWM thresh.	197	98	658	258
[mm/s]		100	100	3	30
OT prewarn	false	false	false	false
triggered
 OTP		false	false	false	false
off time	3	3	3	3
blank time	24	24	24	24
hysteresis
 -end		-1	-1	-1	-1
 -start		1	1	1	1
Stallguard thrs	0	0	0	0
DRVSTATUS	X	Y	Z	E
sg_result	0	0	0	0
stst
olb		*
ola		*
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0x80:0C:00:C0
		Y	0xC0:0C:00:00
		Z	0xC0:0C:00:00
		E	0xC0:0C:00:00
Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing E connection... OK

**Comment by statiealexandru** [comment]
Possible solution: 

You have disabled the dedicated enabled pins.
Please read the following and disable it in your Configuration_adv.h

/**
   * Software enable
   *
   * Use for drivers that do not use a dedicated enable pin, but rather handle the same
   * function through a communication line such as SPI or UART.
   */
  #define SOFTWARE_DRIVER_ENABLE

**Comment by AncientAEON** [comment]
that worked!!!! thank you very much!!!

**Comment by gaby64** [comment]
after much searching, this was the answer!
